apiVersion: v1
kind: Pod
metadata:
  name: web-app
  namespace: test-example
  labels:
     name: web-app
     app: demo
spec:
   containers:
     - name: web-app-demo
       image: web-app:latest
       ports:
         - name: web
           containerPort: 5000
           protocol: TCP
       resources:
          limits:
           memory: "200Mi"
