apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  labels:
    name: web-app
    app: demo
spec:
   ports:
   - port: 5000
     name: web-app
     targetPort: 5000
   selector: 
      name: web-app
