apiVersion: "v1"
kind: Pod
metadata:
  name: mysql-systemlog-pod
  labels:
    name: mysql-systemlog-pod
    app:  demo
spec:
  containers:
    - name: mysql
      image: mysql:5.7.25
      ports:
        - containerPort: 3306         
          protocol: TCP
      env: 
        - 
          name: "MYSQL_ROOT_PASSWORD"
          value: "password1234"
    
