apiVersion: v1
kind: Service
metadata:
  name: mysql-systemlog-svc
  labels:
    name: mysql-demo-systemlog-svc
    app: demo  
spec:
  ports:
  - port: 3306
    name: mysql
    targetPort: 3306
  selector:
    name: mysql-systemlog-pod
    app: demo
