apiVersion: v1
kind: Service
metadata:
  name: web-app-systemlog-svc
  labels:
    name: web-app-systemlog-svc
    app: demo
spec:
  selector:
    name: web-app-systemlog 
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
